language: python
python:
- "3.7"
deploy:
  provider: pypi
  user: jonkerj
  password:
    secure: LA0wpNeWuS+vGrJ4RffkW94OkmWOqNnGOfX/K4OIEwcTuqKR84NQqdWw4gQUtk2XcUFVwaQdkfVSEwU0HxNclriPQxk7hm/HnDaYdMTeI0IrsgmfNl5q2brfUoUoUC1naeBhwfskyXnZpgRmCN8dewvdqtpMtbqSdiTUqnICu+uCaLdlcoB39EZvTXtkrt7Y7YBeQHo2ABl6qQvP5hec5DOwHIqew7NemrUfSRzUrj60jfAHnNrunGmOVpl2D6pCUmeNGeWIpaDiz7f+pCyg/oo6xAJC9VHK6eWIYm6sDhExHAJ/LzaslPxD+aHcebTF6bbMQu50/sRuC0H3BR/lJVAm9aamAxH/1loEZBpOLbzC95tM9WTuxsDFnwCNzd2DEaOyAeIXU6FfIrzDXXTjJbKGz8WNCR8J2p/S4Rh7//8VPnGRaNHbMgusGH7rZWbpdBJVwhrSZTJdmumED3Mj9dIdgU1a9NSEFuOiNYyDac99hFyGMOUk40szuqByTntpj2RQsm8h8Sqro2B7Tdsl5jIgFHtCs2S4oUv8lnqmRPStIzJMZc8tybwgKkPZ9DoRMFcdjTEG5mijVx+8vhfdwsCHE0i4aavw6dd+eDsP3rZ4yanVXAcLtfWkzk0UUt0PwQ9D6G7S8DtSvizpDnHKXjtoFJhUghX8xKaICwCfsGE=
